name: snapshot

on:
  schedule:
    - cron: "0 0 1 * *" #run every month
  workflow_dispatch: #manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: agusalex/grive2
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tags: "snapshot"
