name: release
on:
  release:
    types: [published]
  workflow_dispatch: #manual run
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - 
        name: CheckOut
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push release
        id: docker_build
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: agusalex/grive2:${{ github.ref }}
      - name: Build and push latest
        id: docker_build2
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: agusalex/grive2:latest
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
