name: ci

on:
  push:
    branches: master
  schedule:
    - cron: "0 0 1 * *" #run every month

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: agusalex/grive2:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
